"""new user

Revision ID: 059205334fc9
Revises: 8018cde6dd74
Create Date: 2019-12-09 20:32:29.817365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059205334fc9'
down_revision = '8018cde6dd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_photo', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_photo')
    # ### end Alembic commands ###
